name: klutter
description: Write Flutter plugins for both Android and iOS using Kotlin only.
version: 1.0.1
homepage: https://buijs.dev
repository: https://github.com/buijs-dev/klutter-dart

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  dart_style: ^2.3.0

dev_dependencies:
  coverage: ^1.6.3
  dartdoc: ^6.2.1
  test: ^1.24.1