name: klutter
description: The Klutter Pub Plugin makes it possible to write a Flutter plugin for both Android and iOS using Kotlin only.
version: 0.1.2
homepage: https://buijs.dev
repository: https://github.com/buijs-dev/klutter-dart

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  dart_style: ^2.2.3

dev_dependencies:
  coverage: ^1.3.2
  dartdoc: ^5.1.2
  test: ^1.19.5