name: klutter
description: The Klutter Pub Plugin makes it possible to write a Flutter plugin for both Android and iOS using Kotlin only.
version: 0.1.0
homepage: https://github.com/buijs-dev/klutter-dart
repository: https://github.com/buijs-dev/klutter-dart

environment:
  sdk: ">=2.15.1 <3.0.0"

dev_dependencies:
  coverage: ^1.3.2

  # Used to package binary project files.
  resource_importer: ^0.1.0+1

  test: ^1.19.5

resource_importer:
  resources:
    gradlew_sh: 'res/gradlew'
    gradlew_bat: 'res/gradlew.bat'
    gradle_properties: 'res/gradle.properties'
