name: klutter
description: Write Flutter plugins for both Android and iOS using Kotlin only.
version: 2.1.0
homepage: https://buijs.dev
repository: https://github.com/buijs-dev/klutter-dart

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  dart_style: ^2.2.4 # can be bumped when min SDK is 2.19.0

dev_dependencies:
  coverage: ^1.6.4
  dartdoc: ^6.1.0 # can be bumped when min SDK is 2.19.0
  pana: ^0.22.2
  test: ^1.24.1